function AcceptableUse() {
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '40px 20px' }}>
      <h1 style={{ fontSize: '2rem', color: 'var(--primary)', marginBottom: 8 }}>Acceptable Use Policy</h1>
      <p style={{ color: 'var(--text-light)', marginBottom: 32, fontSize: '0.9rem' }}>
        Last updated: March 21, 2026
      </p>

      <div style={{ lineHeight: 1.8, color: 'var(--text)' }}>
        <h2 style={{ fontSize: '1.25rem', color: 'var(--primary)', marginTop: 32, marginBottom: 12 }}>
          1. Purpose
        </h2>
        <p>
          This Acceptable Use Policy outlines acceptable and prohibited uses of AuditWise Pro ("the Service"). By using the Service, you agree to comply with this policy. Violations may result in suspension or termination of your account.
        </p>

        <h2 style={{ fontSize: '1.25rem', color: 'var(--primary)', marginTop: 32, marginBottom: 12 }}>
          2. Acceptable Use
        </h2>
        <p>
          You may use the Service to scan websites you own or have explicit authorization to audit. You may use scan results to improve your own websites or provide professional audit services to your clients with their consent. You may share reports generated by the Service with authorized stakeholders for legitimate business purposes.
        </p>

        <h2 style={{ fontSize: '1.25rem', color: 'var(--primary)', marginTop: 32, marginBottom: 12 }}>
          3. Prohibited Use
        </h2>
        <p>The following activities are strictly prohibited:</p>
        <ul style={{ paddingLeft: 24, marginTop: 8 }}>
          <li>Scanning websites without authorization from the website owner</li>
          <li>Using the Service to identify vulnerabilities for malicious exploitation</li>
          <li>Automated or scripted mass scanning beyond your plan limits</li>
          <li>Attempting to overload, disrupt, or interfere with the Service</li>
          <li>Using the Service to compete directly with AuditWise Pro, including scraping or reselling raw scan data</li>
          <li>Uploading malicious content, malware, or harmful code</li>
          <li>Impersonating another person or entity</li>
          <li>Violating any applicable laws or regulations</li>
        </ul>

        <h2 style={{ fontSize: '1.25rem', color: 'var(--primary)', marginTop: 32, marginBottom: 12 }}>
          4. Rate Limits
        </h2>
        <p>
          Each subscription plan has defined scan limits. Exceeding your plan's limits may result in temporary suspension of scanning capabilities until the next billing cycle or until you upgrade to a higher plan. Repeated or intentional abuse of rate limits may result in account suspension.
        </p>

        <h2 style={{ fontSize: '1.25rem', color: 'var(--primary)', marginTop: 32, marginBottom: 12 }}>
          5. Enforcement
        </h2>
        <p>
          Violations of this policy may result in a warning for first-time or minor violations, temporary suspension of your account for repeated or moderate violations, or permanent termination of your account without refund for severe or repeated violations. We reserve the right to determine, at our sole discretion, whether a use of the Service violates this policy.
        </p>

        <h2 style={{ fontSize: '1.25rem', color: 'var(--primary)', marginTop: 32, marginBottom: 12 }}>
          6. Reporting Abuse
        </h2>
        <p>
          If you become aware of any misuse of the Service or violations of this policy, please report it to{' '}
          <a href="mailto:support@auditwisepro.com" style={{ color: 'var(--accent)' }}>
            support@auditwisepro.com
          </a>. We take all reports seriously and will investigate promptly.
        </p>

        <h2 style={{ fontSize: '1.25rem', color: 'var(--primary)', marginTop: 32, marginBottom: 12 }}>
          7. Changes to This Policy
        </h2>
        <p>
          We reserve the right to modify this Acceptable Use Policy at any time. Changes will be posted on this page with an updated "Last updated" date. Continued use of the Service after changes are posted constitutes your acceptance of the revised policy.
        </p>
      </div>
    </div>
  );
}

export default AcceptableUse;
